"""empty message

Revision ID: 275f63c1d57f
Revises: 571d516ffb3e
Create Date: 2026-10-01 00:44:32.910670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275f63c1d57f'
down_revision = '571d516ffb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capacity_tons', sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_column('capacity_tons')
        batch_op.drop_column('truck_type')

    # ### end Alembic commands ###
