"""empty message

Revision ID: 571d516ffb3e
Revises: 
Create Date: 2026-09-30 20:11:10.326471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571d516ffb3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('route_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('origin_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('origin_lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('destination_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('destination_lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fuel_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('toll_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('road_risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weather_risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('optimization_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('routing_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_city_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_city_checkpoints')
    op.drop_table('routes')
    # ### end Alembic commands ###
